import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import'./style.css';
const API=(import.meta as any).env.VITE_API_URL||'http://localhost:8000';
type Tab='Targets'|'Attack Library'|'Run Test'|'Report'|'Live Console';
async function api(path:string,opts:any={}){const r=await fetch(API+path,{headers:{'content-type':'application/json'},...opts});if(!r.ok)throw new Error(await r.text());return r.json()}
function App(){const[tab,setTab]=useState<Tab>('Targets');const[targets,setTargets]=useState<any[]>([]);const[attacks,setAttacks]=useState<any[]>([]);const[run,setRun]=useState<any>();const[report,setReport]=useState<any>();const[error,setError]=useState('');const refresh=()=>Promise.all([api('/targets').then(setTargets),api('/attacks').then(setAttacks)]).catch(e=>setError(e.message));useEffect(()=>{refresh()},[]);
useEffect(()=>{if(!run||run.status==='completed')return;const id=setInterval(()=>api('/tests/'+run.id).then((r:any)=>{setRun(r);if(r.status==='completed')api('/reports/'+r.id).then(setReport)}),1000);return()=>clearInterval(id)},[run]);
return <><header><div><b>PromptGuard</b><span>AI security testing workbench</span></div><i className="status">● deterministic engine ready</i></header><nav>{(['Targets','Attack Library','Run Test','Report','Live Console']as Tab[]).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><main>{error&&<p className="error">{error}</p>}{tab==='Targets'&&<Targets items={targets} done={refresh}/>} {tab==='Attack Library'&&<Library items={attacks}/>} {tab==='Run Test'&&<Runner targets={targets} run={run} start={async(id:number)=>{const x=await api('/tests',{method:'POST',body:JSON.stringify({target_id:id,count:20,mutations:['base64','roleplay_wrap'],variants_per_attack:2})});setRun({id:x.test_run_id,status:'queued',executed:0,total:0});}}/>} {tab==='Report'&&<Report report={report}/>} {tab==='Live Console'&&<Console targets={targets}/>}</main></>}
function Targets({items,done}:any){const[form,setForm]=useState({name:'My Chatbot',api_endpoint:'http://target-demo:8001/v1/chat/completions',authorized:false});return <section><h1>Authorized targets</h1><p>Register an HTTP chatbot you own or have explicit permission to test.</p><div className="grid"><form className="card" onSubmit={async e=>{e.preventDefault();await api('/targets',{method:'POST',body:JSON.stringify({...form,canary:'GENESIS-7731-INTERNAL'})});done()}}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Endpoint<input value={form.api_endpoint} onChange={e=>setForm({...form,api_endpoint:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.authorized} onChange={e=>setForm({...form,authorized:e.target.checked})}/> I confirm authorization to security-test this target.</label><button className="primary" disabled={!form.authorized}>Register target</button></form><div>{items.map((x:any)=><article className="card"><b>{x.name}</b><code>{x.api_endpoint}</code><span className="pill">AUTHORIZED</span></article>)}</div></div></section>}
function Library({items}:any){const[q,setQ]=useState('');const visible=items.filter((x:any)=>(x.title+x.category+x.prompt).toLowerCase().includes(q.toLowerCase()));return <section><h1>Attack library <em>{items.length} patterns</em></h1><input className="search" placeholder="Search category, title, or payload" value={q} onChange={e=>setQ(e.target.value)}/><div className="table"><div className="tr head"><span>ID</span><span>Category</span><span>Attack</span><span>Severity</span></div>{visible.map((a:any)=><details className="tr"><summary><span>{a.id}</span><span>{a.category.replaceAll('_',' ')}</span><span>{a.title}</span><span className={'sev '+a.source_severity}>{a.source_severity}</span></summary><div className="detail"><code>{a.prompt}</code><p><b>Expected:</b> {a.expected_safe_behaviour}</p><p><b>Fix:</b> {a.remediation}</p></div></details>)}</div></section>}
function Runner({targets,run,start}:any){const[id,setId]=useState(targets[0]?.id);useEffect(()=>{if(!id&&targets[0])setId(targets[0].id)},[targets]);const pct=run?.total?100*run.executed/run.total:0;return <section><h1>Run a batch assessment</h1><div className="card runner"><label>Target<select value={id} onChange={e=>setId(+e.target.value)}>{targets.map((x:any)=><option value={x.id}>{x.name}</option>)}</select></label><p>20 curated attacks · base64 and role-play mutations · request blocking off for learning mode</p><button className="primary" onClick={()=>start(id)} disabled={!id||run?.status==='running'}>Start security test</button>{run&&<div className="progress"><b>{run.status.toUpperCase()}</b><span>{run.executed}/{run.total||'…'}</span><div><i style={{width:pct+'%'}}/></div></div>}</div></section>}
function Report({report}:any){if(!report)return <section><h1>Report</h1><div className="empty">Complete a run to generate the evidence report.</div></section>;return <section><div className="title"><div><h1>Security assessment</h1><p>{report.target_name}</p></div><a className="primary" href={API+'/reports/'+report.run_id+'?format=md'}>Export Markdown</a></div><div className="kpis"><K label="Risk score" v={report.risk_score_overall}/>{Object.entries(report.totals).slice(0,5).map(([k,v])=><K label={k} v={v}/>)}</div><h2>Findings</h2>{report.findings.map((f:any)=><details className={'finding '+f.outcome}><summary><b>{f.outcome}</b><span>{f.category.replaceAll('_',' ')}</span><span>{f.title}</span><i>{f.derived_severity}</i></summary><div className="detail"><p><b>Sent</b></p><code>{f.payload_used}</code><p><b>Request gate:</b> {f.request_verdict}; reached target: {String(f.reached_target)}</p><p><b>Target response</b></p><code>{f.response_excerpt}</code><p className="fix"><b>Recommended fix:</b> {f.remediation}</p></div></details>)}</section>}
function K({label,v}:any){return <div className="card kpi"><span>{label.replaceAll('_',' ')}</span><b>{String(v)}</b></div>}
function Console({targets}:any){const[id,setId]=useState(targets[0]?.id);const[msg,setMsg]=useState('');const[result,setResult]=useState<any>();return <section><h1>Live inspection console</h1><div className="card console"><select value={id} onChange={e=>setId(+e.target.value)}>{targets.map((x:any)=><option value={x.id}>{x.name}</option>)}</select><textarea placeholder="Type a message or injection attempt…" value={msg} onChange={e=>setMsg(e.target.value)}/><button className="primary" onClick={async()=>setResult(await api('/proxy/chat',{method:'POST',body:JSON.stringify({target_id:id,session_id:'ui-live',message:msg})}))}>Inspect and send</button>{result&&<div className="result"><div className="pipeline"><span>Decode ✓</span><span>Rules ✓</span><span>Similarity ✓</span><span>{result.request_verdict.action}</span></div><pre>{result.response||result.notice}</pre></div>}</div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
